// Adapted from https://en.wikipedia.org/wiki/List_of_musical_instruments
import { OptionGroup } from 'react-querybuilder';

export const musicalInstruments: OptionGroup[] = [
  {
    label: 'Percussion instruments',
    instruments: [
      'Afoxé',
      'Agogô',
      'Agung',
      'Angklung',
      'Babendil',
      'Bak',
      'Bamileke',
      'Balafon',
      'Batá drum',
      'Cabasa',
      'Cajón',
      'Carillon',
      'Castanets',
      'Caxirola',
      'Caxixi',
      'Chácaras',
      'Clapstick',
      'Claves',
      'Cowbell',
      'Crotales',
      'Cymbal',
      'Ferrinho',
      'Flexatone',
      'Octa-Vibraphone',
      'Gandingan',
      'Ghatam',
      'Glockenspiel',
      'Gong',
      'Güiro',
      'Handpan',
      'Hang',
      'Kayamb',
      'Kemanak',
      'Khartal',
      'Kouxian',
      'Kulintang',
      'Maraca',
      'Marimba',
      'Mbira',
      'Pate',
      'Shekere',
      'Slit drum',
      'Spoon',
      'Steelpan',
      'Tambourine',
      'Teponaztli',
      'Triangle',
      'Txalaparta',
      'Vibraphone',
      'Vibraslap',
      'Washboard',
      'Wood block',
      'Wooden fish',
      'Xylophone',
      'Zill',
    ],
  },
  {
    label: 'Membranophones',
    instruments: [
      'Agida',
      'Alfaia',
      'Apinti',
      'Arobapá',
      'Ashiko',
      'Atabaque',
      'Baboula',
      'Balaban',
      'Balsié',
      'Bamboula',
      'Bara',
      'Barrel drum',
      'Barriles',
      'Bass drum',
      'Bedug',
      'Bodhrán',
      'Bongo drums',
      'Boobam',
      'Candombe',
      'Chenda',
      'Conga',
      'Cuíca',
      'Culoepuya',
      'Dabakan',
      'Daf',
      'Damaru',
      'Davul',
      'Dayereh',
      'Den-den daiko',
      'Dhak',
      'Dhimay',
      'Dhol',
      'Dholak',
      'Dimdi',
      'Djembe',
      'Dollu',
      'Drum',
      'Drum kit',
      'Dunun',
      'Bass Drum',
      'Goblet drum',
      'Gong bass drum',
      'Hira-daiko',
      'Idakka',
      'Ilimba drum',
      'Ingoma',
      'Janggu',
      "Jew's harp",
      'Junjung',
      'Kakko',
      'Kanjira',
      'Kebero',
      'Kendang',
      'Khol',
      'Krakebs',
      'Lambeg drum',
      'Madhalam',
      'Madal',
      'Maddale',
      'Maktoum',
      'Maram',
      'Mirwas',
      'Mridangam',
      'Nagara',
      'Naqareh',
      'O-daiko',
      'Okedo-daiko',
      'Octaban',
      'Padayani thappu',
      'Pakhavaj',
      'Pandero',
      'Parai',
      'Qilaut',
      'Rebana',
      'Sabar',
      'Sambal',
      'Samphor',
      'Shime-daiko',
      'Snare drum',
      'Surdo',
      'Tabla',
      'Taiko',
      'Talking drum',
      'Tsukeshime-daiko',
      'Tambor huacana',
      'Tambori',
      'Tamborim',
      'Tamborita calentana',
      'Tambou bas a dé fas',
      'Tambou bas a yon fas',
      'Tan-tan',
      'Taphon',
      'Tar',
      'Tbilat',
      'Thavil',
      'Timbales',
      'Timpani',
      'Tom-tom',
      'Tombak',
      'Tsuzumi',
      'Tsuri-daiko',
      'Repique',
      'Uchiwa-daiko',
    ],
  },
  {
    label: 'Wind instruments',
    instruments: [
      'Aztec Death Whistle',
      'Accordina',
      'Accordion',
      'Accordola',
      'Air horn',
      'Alboka',
      'Algaita',
      'Alphorn',
      'Alto horn',
      'Arghul',
      'Atenteben',
      'Aulos',
      'Bagpipe',
      'Bandoneón',
      'Bansuri',
      'Baritone horn',
      'Baritone',
      'Bassoon',
      'Bawu',
      'Bayan',
      'Bazooka',
      'Beatboxing',
      'Bifora',
      'Birbynė',
      'Blul',
      'Blown bottle',
      'Bombarde',
      'Buccina',
      'Bugle',
      'Bullroarer',
      'Calliope',
      'Castrato',
      'Chalumeau',
      'Cimbasso',
      'Clarinet',
      'Clarytone',
      'Concertina',
      'Conch',
      'Cornamuse',
      'Cornet',
      'Cornett',
      'Cornu',
      'Corrugaphone',
      'Countertenor',
      'Cromorne',
      'Crumhorn',
      'Danso',
      'Death growl',
      'Didgeridoo',
      'Diple',
      'Dizi',
      'Double bell euphonium',
      'Doulophone',
      'Duduk',
      'Dulcian',
      'Dulzaina',
      'Dung-Dkar',
      'Dzhamara',
      'English horn',
      'Euphonium',
      'Fife',
      'Firebird',
      'Fiscorn',
      'Flabiol',
      'Flageolet',
      'Flugelhorn',
      'Flumpet',
      'Flutina',
      'Flute',
      'Folgerphone',
      'French horn',
      'Fujara',
      'Gaida',
      'Gaita gastoreña',
      'Garmon',
      'Gemshorn',
      'Gralla',
      'Guan',
      'Hano',
      'Harmoneon',
      'Harmonica',
      'Harmonium',
      'Heckelphone',
      'Helicon',
      'Horagai',
      'Hosaphone',
      'Hotchiku',
      'Hulusi',
      'Hun',
      'Inci Özdil',
      'Irish flute',
      'Jug',
      'Kagurabue',
      'Kalaleng',
      'Kaval',
      'Kazoo',
      'Kèn bầu',
      'Key bugle',
      'Khene',
      'Khloy',
      'Khlui',
      'Komabue',
      'Kombu',
      'Koncovka',
      'Kortholt',
      'Koudi',
      'Kuhlohorn',
      'Kuzhal',
      'Launeddas',
      'Livenka',
      'Lur',
      'Lusheng',
      'Lituus',
      'Mellophone',
      'Melodica',
      'Melodeon',
      'Mezzo-soprano',
      'Mijwiz',
      'Mizmar',
      'Mizwad',
      'Musette de cour',
      'Nadaswaram',
      'Nagak',
      'Natural trumpet',
      'Ney',
      'Nguru',
      'Nohkan',
      'Nose flute',
      'Nplooj',
      'Nulophone',
      'Oboe',
      'Ocarina',
      'Octavin',
      'Ophicleide',
      'Paixiao',
      'Palendag',
      'Pan flute',
      'Pasiyak',
      'Pavari',
      'Pibgorn',
      'Picco pipe',
      'Piccolo',
      'Piccolo trumpet',
      'Pipe organ',
      'Pitch pipe',
      'Pocket cornet',
      'Pocket trumpet',
      'Post horn',
      'Pu',
      'Pulalu',
      'Qeej',
      'Quena',
      'Quinticlave',
      'Raj',
      'Rackett',
      'Ralé-poussé',
      'Rapping',
      'Rauschpfeife',
      'Recorder',
      'Reed contrabass',
      'Reed organ',
      'Rhaita',
      'Robero',
      'Roman tuba',
      'Ryuteki',
      'Sac de gemecs',
      'Sackbut',
      'Saenghwang',
      'Samponia',
      'Saratovskaya garmonika',
      'Sarrusophone',
      'Saxophone',
      'Saxhorn',
      'Saxotromba',
      'Saxtuba',
      'Scat singing',
      'Schwyzerörgeli',
      'Serpent',
      'Shakuhachi',
      'Shankha',
      'Shawm',
      'Shehnai',
      'Sheng',
      'Shinobue',
      'Shofar',
      'Shō',
      'Shvi',
      'Siku',
      'Siren',
      'Slide trumpet',
      'Slide whistle',
      'Sneng',
      'Sodina',
      'Sopila',
      'Soprano',
      'Sorna',
      'Sousaphone',
      'Sralai',
      'Sudrophone',
      'Suling',
      'Suona',
      'Superbone',
      'Swordblade',
      'Tabor pipe',
      'Taepyeongso',
      'Tarogato',
      'Tenor',
      'Tenora',
      'Throat singing',
      'Tible',
      'Tin whistle',
      'Toasting',
      'Tonette',
      'Trikiti',
      'Trombone',
      'Tromboon',
      'Trompeta china',
      'Trumpet',
      'Tuba',
      'Tube trumpet',
      'Tumpong',
      'Tungso',
      'Tutek',
      'Txistu',
      'Uilleann pipes',
      'Venu',
      'Vibrandoneon',
      'Vienna horn',
      'Vocal percussion',
      'Vuvuzela',
      'Wagner tuba',
      'Washint',
      'Western concert flute',
      'Whip',
      'Whistle',
      'Willow flute',
      'Xeremia',
      'Xiao',
      'Xun',
      'Yotar',
      'Yu',
      'Zhaleika',
      'Zufolo',
      'Zugtrompette',
      'Zurna',
    ],
  },
  {
    label: 'Stringed instruments',
    instruments: [
      'Adungu',
      'Aeolian harp',
      'Ajaeng',
      'Akkordolia',
      'Algerian mandole',
      'Angélique',
      'Appalachian dulcimer',
      'Arbajo',
      'Archlute',
      'Arpeggione',
      'Autoharp',
      'Bağlama',
      'Bajo sexto',
      'Balalaika',
      'Bandola',
      'Bandolin',
      'Bandolón',
      'Bandura',
      'Bandora',
      'Bandurria',
      'Banhu',
      'Banjo',
      'Banjo ukulele',
      'Barbat',
      'Baryton',
      'Berimbau',
      'Bipa',
      'Biwa',
      'Bordonua',
      'Bouzouki',
      'Buzuq',
      'Carimba',
      'Cavaquinho',
      'Cello',
      'Chapman stick',
      'Charango',
      'Chitarra battente',
      'Chitarra Italiana',
      'Choghur',
      'Cimbalom',
      'Cimboa',
      'Citole',
      'Cittern',
      'Clavichord',
      'Clavinet',
      'Concheras',
      'Contraguitar',
      'Crwth',
      'Cuatro',
      'Cümbüş',
      'Đàn bầu',
      'Đàn đáy',
      'Đàn gáo',
      'Đàn nguyệt',
      'Đàn tam thập lục',
      'Đàn tranh',
      'Đàn tỳ bà',
      'Diddley bow',
      'Dihu',
      'Dombra',
      'Domra',
      'Doshpuluur',
      'Dotara',
      'Double bass',
      'Dreadnought',
      'Dulcimer',
      'Dutar',
      'Duxianqin',
      'Ektara',
      'Erhu',
      'Erxian',
      'Esraj',
      'Faglong',
      'Fegereng',
      'Fiddle',
      'Gaohu',
      'Gayageum',
      'Geomungo',
      'Gittern',
      'Gottuvadhyam',
      'Guitar',
      'Guitarra de golpe',
      'Guitarra panzona',
      'Guitarra séptima',
      'Guitarro',
      'Gusli',
      'Guqin',
      'Guzheng',
      'Haegeum',
      'Hammered dulcimer',
      'Hardanger fiddle',
      'Harmonico',
      'Harp',
      'Harp guitar',
      'Harpsichord',
      'Hegelong',
      'Huapanguera',
      'Huluhu',
      'Huqin',
      'Hurdy-gurdy',
      'Igil',
      'Irish bouzouki',
      'Janzi',
      'Jarana jarocho',
      'Jarana huasteca',
      'Jarana mosquito',
      'Jarana segunda',
      'Jarana tercera',
      'Jiaohu',
      'Kabosy',
      'Kadlong',
      'Kamancha',
      'Kantele',
      'Kemenche',
      'Khim',
      'Kobza',
      'Kokle',
      'Kokyū',
      'Komuz',
      'Kora',
      'Koto',
      'Kubing',
      'Kudyapi',
      'Kwitra',
      'Langeleik',
      'Laouto',
      'Laruan',
      'Laúd',
      'Lavta',
      'Leiqin',
      'Leona',
      'Lirone',
      'Liuqin',
      'Lokanga bara',
      'Lute',
      'Lute guitar',
      'Lyra',
      'Lyre',
      'Maguhu',
      'Mandobass',
      'Mandola',
      'Mandolin',
      'Mandolute',
      'Mandora',
      'Mandore',
      'Marovany',
      'Mejoranera',
      'Mexican vihuela',
      'Mohan veena',
      'Moraharpa',
      'Morin khuur',
      'Musical bow',
      'Nyckelharpa',
      'Octobass',
      'Oud',
      'Paqin',
      'Piano',
      'Pipa',
      'Piwancha',
      'Pochette',
      'Portuguese guitar',
      'Psaltery',
      'Qanun',
      'Qinqin',
      'Rabeca',
      'Rajão',
      'Ravanahatha',
      'Rebab',
      'Rebec',
      'Requinto jarocho',
      'Rubab',
      'Ruan',
      'Rudra vina',
      'Sallameh',
      'Sanshin',
      'Santoor',
      'Sanxian',
      'Sarangi',
      'Šargija',
      'Sarod',
      'Saung',
      'Saw sam sai',
      'Se',
      'Seul',
      'Setar',
      'Shamisen',
      'Sintir',
      'Sitar',
      'Sitarla',
      'Surbahar',
      'Swarmandal',
      'Tamburica',
      'Tambur',
      'Tanpura',
      'Tea chest bass',
      'Tembûr',
      'Theorbo',
      'Timple',
      'Tiple',
      'Tovshuur',
      'Tres',
      'Tricordia',
      'Tro',
      'Trumpet marine',
      'Tsymbaly',
      'Tuhu',
      'Tzouras',
      'Ukulele',
      'Ukelin',
      'Valiha',
      'Veena',
      'Vertical viola',
      'Vichitra veena',
      'Vielle',
      'Vihuela',
      'Viol',
      'Viola da gamba',
      'Viola amarantina',
      'Viola bastarda',
      'Viola beiroa',
      'Viola caipira',
      "Viola d'amore",
      'Viola da terra',
      'Viola de arame',
      'Viola de cocho',
      'Viola organista',
      'Viola profonda',
      'Violin',
      'Violone',
      'Violotta',
      'Walaycho',
      'Waldzither',
      'Washtub bass',
      'Whamola',
      'Wheelharp',
      'Xalam',
      'Yaylı tambur',
      'Yangqin',
      'Yazheng',
      'Yehu',
      'Yelatáj chos woley',
      'Yueqin',
      'Zhongruan',
      'Zhonghu',
      'Zhu',
      'Zhengni',
      'Zhuihu',
      'Zither',
    ],
  },
  {
    label: 'Electronic instruments',
    instruments: [
      'AlphaSphere',
      'Audiocubes',
      'Bass pedals',
      'Continuum Fingerboard',
      'Croix Sonore',
      "Denis d'or",
      'Dubreq stylophone',
      'Drum machine',
      'Eigenharp',
      'Electric guitar',
      'Electronic keyboard',
      'Electronic organ',
      'EWI',
      'Fingerboard synthesizer',
      'Hammond organ',
      'Keyboard]',
      'Keytar',
      'Kraakdoos',
      'Laser harp',
      'Mellotron',
      'MIDI keyboard',
      'Omnichord',
      'Ondes Martenot',
      'Otamatone',
      'Sampler',
      'Seaboard music instrument',
      'Skoog',
      'Synclavier',
      'Synthesizer',
      'Teleharmonium',
      'Tenori-on',
      'Theremin',
      'trautonium',
      'Turntablism',
      'Turntable',
    ],
  },
].map(({ label, instruments }) => ({
  label,
  options: instruments.map(s => ({ name: s, label: s })),
}));
