import type { RulesLogic } from 'json-logic-js';
import type { ComponentType, ReactNode } from 'react';
import type { FullOption, RQBJsonLogic, RuleProcessor, ValueEditorProps } from 'react-querybuilder';

export interface RQBJsonLogicDateBetween {
  dateBetween: [RQBJsonLogic, RQBJsonLogic, RQBJsonLogic];
}
export interface RQBJsonLogicDateNotBetween {
  dateNotBetween: [RQBJsonLogic, RQBJsonLogic, RQBJsonLogic];
}
export interface RQBJsonLogicDateIn {
  dateIn: [RQBJsonLogic, RQBJsonLogic[]];
}
export interface RQBJsonLogicDateNotIn {
  dateNotIn: [RQBJsonLogic, RQBJsonLogic[]];
}
export interface RQBJsonLogicDateBefore {
  dateBefore: [RQBJsonLogic, RQBJsonLogic, ...RQBJsonLogic[]];
}
export interface RQBJsonLogicDateOnOrBefore {
  dateOnOrBefore: [RQBJsonLogic, RQBJsonLogic, ...RQBJsonLogic[]];
}
export interface RQBJsonLogicDateOn {
  dateOn: [RQBJsonLogic, RQBJsonLogic, ...RQBJsonLogic[]];
}
export interface RQBJsonLogicDateNotOn {
  dateNotOn: [RQBJsonLogic, RQBJsonLogic, ...RQBJsonLogic[]];
}
export interface RQBJsonLogicDateAfter {
  dateAfter: [RQBJsonLogic, RQBJsonLogic, ...RQBJsonLogic[]];
}
export interface RQBJsonLogicDateOnOrAfter {
  dateOnOrAfter: [RQBJsonLogic, RQBJsonLogic, ...RQBJsonLogic[]];
}
export interface RQBJsonLogicDateRelative {
  dateRelative: [RelativeDateTimeAnchor, number, RelativeDateTimeUnit, boolean];
}

/**
 * JsonLogic rule object with additional operators generated by
 * {@link @react-querybuilder/core!formatQuery formatQuery} and accepted by
 * {@link @react-querybuilder/core!parseJsonLogic parseJsonLogic}.
 */
export type RQBDateTimeJsonLogic =
  | RQBJsonLogic
  | RulesLogic<
      | RQBJsonLogicDateAfter
      | RQBJsonLogicDateBefore
      | RQBJsonLogicDateBetween
      | RQBJsonLogicDateIn
      | RQBJsonLogicDateNotBetween
      | RQBJsonLogicDateNotIn
      | RQBJsonLogicDateNotOn
      | RQBJsonLogicDateOn
      | RQBJsonLogicDateOnOrAfter
      | RQBJsonLogicDateOnOrBefore
      | RQBJsonLogicDateRelative
    >;

type DateOrString = string | Date;

/**
 * Unit of measure for a relative date/time offset.
 */
export type RelativeDateTimeUnit = 'minute' | 'hour' | 'day' | 'week' | 'month' | 'year';

/**
 * Unit of measure for truncating a date/time to the start or end of a period
 * (the subset of {@link RelativeDateTimeUnit} that represents a calendar period).
 */
export type RelativeDateTimeTruncationUnit = 'day' | 'week' | 'month' | 'year';

/**
 * Reference point (zero-offset) for a {@link RelativeDateTimeValue}. `'now'` is the
 * current date/time; the `startOf*`/`endOf*` anchors truncate to the start or end
 * of the corresponding calendar period.
 */
export type RelativeDateTimeAnchor =
  | 'now'
  | 'startOfDay'
  | 'endOfDay'
  | 'startOfWeek'
  | 'endOfWeek'
  | 'startOfMonth'
  | 'endOfMonth'
  | 'startOfYear'
  | 'endOfYear';

/**
 * Structured representation of a relative date/time value, e.g. "three months ago"
 * or "the beginning of this year". Stored as the `value` of a rule (in place of the
 * usual ISO 8601 string) and recognized by the date/time rule processors.
 *
 * The final date/time is computed as: apply the `anchor` to the current date/time,
 * then add `offset` units of `unit`. When `offset` is `0`, `unit` is irrelevant.
 */
export interface RelativeDateTimeValue {
  /** Discriminant identifying a relative (as opposed to absolute) value. */
  mode: 'relative';
  /** Zero-offset reference point. */
  anchor: RelativeDateTimeAnchor;
  /** Signed offset from the anchor; negative = past, positive = future, 0 = exact anchor. */
  offset: number;
  /** Unit of the `offset`. */
  unit: RelativeDateTimeUnit;
}

export interface RQBDateTimeLibraryAPI {
  /**
   * Formats a date as a string.
   */
  format: (d: DateOrString, fmt: string) => string;
  /**
   * Formats a date as an ISO 8601 string, only including
   * the year, month, and day ('YYYY-MM-DD').
   */
  toISOStringDateOnly: (d: DateOrString) => string;
  /**
   * Determines whether the first date is after the second date.
   */
  isAfter: (a: DateOrString, b: DateOrString) => boolean;
  /**
   * Determines whether the first date is before the second date.
   */
  isBefore: (a: DateOrString, b: DateOrString) => boolean;
  /**
   * Determines whether the first date is the same as the second date.
   *
   * If either the first date or the second date is a string in the
   * format 'YYYY-MM-DD', then the dates will only be compared at
   * the date level (no time component). Otherwise, they will be
   * compared to the millisecond.
   */
  isSame: (a: DateOrString, b: DateOrString) => boolean;
  /**
   * Determines whether the date is either a valid `Date` object or an
   * ISO 8601-formatted string representing a valid date.
   */
  isValid: (d: DateOrString) => boolean;
  /**
   * Converts a string to a `Date` object or returns a valid `Date` as is.
   */
  toDate: (d: DateOrString) => Date;
  /**
   * Converts a `Date` or ISO 8601-formatted string into a full ISO 8601 UTC
   * string, in the format 'YYYY-MM-DDTHH:mm:ss.SSSZ' (the "T" and "Z" are
   * static; other parts represent standard time units, increasing in precision
   * from left to right).
   */
  toISOString: (d: DateOrString) => string;
  /**
   * Returns a new `Date` truncated to the start of the given period.
   *
   * Week start follows the date library's own default/locale (e.g. Luxon uses
   * Monday per ISO 8601; Day.js and date-fns default to Sunday).
   */
  startOf: (d: DateOrString, unit: RelativeDateTimeTruncationUnit) => Date;
  /**
   * Returns a new `Date` advanced to the end of the given period (the last
   * representable instant within it).
   *
   * Week start follows the date library's own default/locale (see {@link RQBDateTimeLibraryAPI.startOf}).
   */
  endOf: (d: DateOrString, unit: RelativeDateTimeTruncationUnit) => Date;
  /**
   * Returns a new `Date` offset from the input by `amount` units of `unit`
   * (negative `amount` moves into the past).
   */
  add: (d: DateOrString, amount: number, unit: RelativeDateTimeUnit) => Date;
}

type FnDateDate = (a: DateOrString, b: DateOrString) => boolean;
type FnDateArrayOfDates = (a: DateOrString, b: DateOrString[]) => boolean;
type FnDateDateDate = (a: DateOrString, b: DateOrString, c: DateOrString) => boolean;

export type RQBJsonLogicDateTimeOperations = {
  /** Determines if the first date is after the second date. */
  dateAfter: FnDateDate;
  /** Determines if the first date is before the second date. */
  dateBefore: FnDateDate;
  /** Determines if the second date is between the first and third dates (inclusive). */
  dateBetween: FnDateDateDate;
  /** Determines if the first date is one of the values in the array of dates. */
  dateIn: FnDateArrayOfDates;
  /** Determines if the second date is not between the first and third dates. */
  dateNotBetween: FnDateDateDate;
  /** Determines if the first date is not one of the values in the array of dates. */
  dateNotIn: FnDateArrayOfDates;
  /** Determines if the first date is not the same as the second date. */
  dateNotOn: FnDateDate;
  /** Determines if the first date is the same as the second date (at the level of least precision between the two). */
  dateOn: FnDateDate;
  /** Determines if the first date is either the same as the second date or after it. */
  dateOnOrAfter: FnDateDate;
  /** Determines if the first date is either the same as the second date or before it. */
  dateOnOrBefore: FnDateDate;
  /**
   * Resolves a relative date/time descriptor (anchor, offset, unit, and date-only
   * flag) to a concrete ISO 8601 string at evaluation time ("live" semantics).
   */
  dateRelative: (
    anchor: RelativeDateTimeAnchor,
    offset: number,
    unit: RelativeDateTimeUnit,
    dateOnly: boolean
  ) => string;
};

/**
 * Customizable content/labels for the absolute/relative mode toggle rendered by
 * {@link toggleModeController}. The default glyphs come from CSS pseudo-elements, so
 * `absoluteContent`/`relativeContent` are only needed to override them (e.g. to render
 * an icon component or localized text).
 */
export interface RelativeDateTimeToggleLabels {
  /** Accessible label (`aria-label`) for the toggle button. */
  label?: string;
  /** Tooltip shown while in absolute mode (clicking switches to relative). */
  absoluteTitle?: string;
  /** Tooltip shown while in relative mode (clicking switches to absolute). */
  relativeTitle?: string;
  /** Custom content rendered while in absolute mode. Defaults to a CSS glyph. */
  absoluteContent?: ReactNode;
  /** Custom content rendered while in relative mode. Defaults to a CSS glyph. */
  relativeContent?: ReactNode;
}

/**
 * Props passed to a {@link RelativeDateTimeModeController}'s `ModeControl` component —
 * the affordance (e.g. a toggle button) that switches a rule between absolute and
 * relative date/time entry.
 */
export interface RelativeDateTimeModeControlProps {
  /** Whether the rule is currently in relative mode. */
  isRelative: boolean;
  /** Switches the rule between absolute and relative mode. */
  setMode: (mode: 'absolute' | 'relative') => void;
  /** The value editor's schema (for theme-aware rendering). */
  schema: ValueEditorProps['schema'];
  /** Whether the control is disabled. */
  disabled?: boolean;
  /** Class name applied to the control. */
  className?: string;
  /** Title/tooltip from the value editor (fallback when labels omit titles). */
  title?: string;
  /** Test ID from the value editor. */
  testID?: string;
  /** Resolved toggle labels (merged with defaults). */
  labels: Required<RelativeDateTimeToggleLabels>;
}

/**
 * A pluggable strategy that governs how a user switches between absolute and relative
 * date/time entry in the {@link RelativeDateTimeValueEditor}. The stored value shape is
 * unaffected — a controller only decides the current mode and (optionally) renders an
 * affordance to change it.
 *
 * Ships with {@link toggleModeController} (the zero-config default); build an
 * operator-driven controller with {@link createOperatorModeController}, or supply a custom
 * object to fully control the UX.
 */
export interface RelativeDateTimeModeController {
  /** Derives the current mode from the rule (its operator and/or value). */
  isRelative: (props: ValueEditorProps) => boolean;
  /**
   * Optional affordance rendered inside the editor to switch modes. Omit it (as the
   * operator-driven controller does) when the mode is selected elsewhere, e.g. via the
   * operator selector.
   */
  ModeControl?: ComponentType<RelativeDateTimeModeControlProps>;
}

/**
 * Configuration for the {@link RelativeDateTimeValueEditor}, supplied as props to
 * {@link QueryBuilderDateTime} (or via the relative date/time config context). Every
 * field is optional; omitting all of them yields the zero-config toggle experience.
 */
export interface RelativeDateTimeEditorConfig {
  /** Strategy for switching between absolute and relative modes. Defaults to {@link toggleModeController}. */
  modeController?: RelativeDateTimeModeController;
  /** Anchor (reference-point) options. Defaults to {@link defaultRelativeDateTimeAnchors}. */
  anchors?: FullOption<RelativeDateTimeAnchor>[];
  /** Unit options. Defaults to {@link defaultRelativeDateTimeUnits}. */
  units?: FullOption<RelativeDateTimeUnit>[];
  /** Content/labels for the absolute/relative toggle. */
  toggleLabels?: RelativeDateTimeToggleLabels;
}

/**
 * Maps operator names that are used only to _signal_ relative mode (see
 * {@link createOperatorModeController}) to the real comparison operator that should be used
 * when exporting via `formatQuery`. Supplied through `context.relativeOperatorMap`. Operators
 * not present in the map are exported unchanged.
 *
 * @example
 * ```ts
 * formatQuery(query, {
 *   format: 'sql',
 *   ruleProcessor: datetimeRuleProcessorSQL,
 *   context: { relativeOperatorMap: { relativeEq: '=' } },
 * });
 * ```
 */
export type RelativeOperatorMap = Record<string, string>;

export type IsDateFieldFunction = (...[rule, opts]: Parameters<RuleProcessor>) => boolean;
export type IsDateField =
  | IsDateFieldFunction
  | Record<string, unknown>
  | Record<string, unknown>[]
  | boolean
  | undefined;
