// @ts-check
/** @type {import('./exampleConfigs').ExampleConfigs} */
export const configs = {
  basic: {
    name: 'Basic',
    dependencies: {},
    scssPre: [],
    scssPost: [],
    tsxImports: [],
    additionalDeclarations: [],
    wrapper: null,
    props: [],
    compileToJS: true,
    isCompatPackage: false,
    enableDnD: false,
  },
  'basic-ts': {
    name: 'Basic TypeScript',
    dependencies: {},
    scssPre: [],
    scssPost: [],
    tsxImports: [],
    additionalDeclarations: [],
    wrapper: null,
    props: [],
    compileToJS: false,
    isCompatPackage: false,
    enableDnD: false,
  },
  dnd: {
    name: 'Drag-and-drop',
    dependencies: { 'react-dnd': '>=14.0.0', 'react-dnd-html5-backend': '>=14.0.0' },
    scssPre: [],
    scssPost: [],
    tsxImports: [`import { QueryBuilderDnD } from '@react-querybuilder/dnd';`],
    additionalDeclarations: [],
    wrapper: ['<QueryBuilderDnD>', '</QueryBuilderDnD>'],
    props: [],
    compileToJS: false,
    isCompatPackage: false,
    enableDnD: true,
  },
  antd: {
    name: 'Ant Design',
    dependencies: { antd: '^4.20.5' },
    scssPre: [`@import 'antd/dist/antd.compact.css';`],
    scssPost: [`.queryBuilder{.ant-input{width:auto;}}`],
    tsxImports: [`import { QueryBuilderAntD } from '@react-querybuilder/antd';`],
    additionalDeclarations: [],
    wrapper: ['<QueryBuilderAntD>', '</QueryBuilderAntD>'],
    props: [],
    compileToJS: false,
    isCompatPackage: true,
    enableDnD: false,
  },
  bootstrap: {
    name: 'Bootstrap',
    dependencies: {
      bootstrap: '^5.1.3',
      'bootstrap-icons': '^1.8.2',
    },
    scssPre: [`$code-color: #333333;`, `@import 'bootstrap/scss/bootstrap.scss';`],
    scssPost: [`.queryBuilder{.form-control,.form-select{display:inline-block;width:auto;}}`],
    tsxImports: [`import { QueryBuilderBootstrap } from '@react-querybuilder/bootstrap';`],
    additionalDeclarations: [],
    wrapper: ['<QueryBuilderBootstrap>', '</QueryBuilderBootstrap>'],
    props: [],
    compileToJS: false,
    isCompatPackage: true,
    enableDnD: false,
  },
  bulma: {
    name: 'Bulma',
    dependencies: { bulma: '^0.9.4' },
    scssPre: [`$code: #333333;`, `$code-background: unset;`, `@import 'bulma/bulma.sass';`],
    scssPost: [`.queryBuilder{.input{width: auto;}}`],
    tsxImports: [`import { QueryBuilderBulma } from '@react-querybuilder/bulma';`],
    additionalDeclarations: [],
    wrapper: ['<QueryBuilderBulma>', '</QueryBuilderBulma>'],
    props: [],
    compileToJS: false,
    isCompatPackage: true,
    enableDnD: false,
  },
  chakra: {
    name: 'Chakra UI',
    dependencies: {
      '@chakra-ui/icons': '^2.0.0',
      '@chakra-ui/react': '^2.0.2',
      '@chakra-ui/system': '^2.0.2',
      '@emotion/react': '^11.9.0',
      '@emotion/styled': '^11.8.1',
      'framer-motion': '^6.3.3',
    },
    scssPre: [],
    scssPost: [
      `.queryBuilder {
        .chakra-select__wrapper {width: fit-content;display: inline-block;}
        .chakra-input {width: auto;display: inline-block;}
        .chakra-radio-group {display: inline-block;}
      }`,
    ],
    tsxImports: [
      `import { ChakraProvider, extendTheme } from '@chakra-ui/react';`,
      `import { QueryBuilderChakra } from '@react-querybuilder/chakra';`,
    ],
    additionalDeclarations: [
      `const chakraTheme = extendTheme({config:{initialColorMode: 'light',useSystemColorMode: false}});`,
    ],
    wrapper: [
      '<ChakraProvider theme={chakraTheme}><QueryBuilderChakra>',
      '</QueryBuilderChakra></ChakraProvider>',
    ],
    props: [],
    compileToJS: false,
    isCompatPackage: true,
    enableDnD: false,
  },
  material: {
    name: 'MUI/Material',
    dependencies: {
      '@emotion/react': '^11.9.0',
      '@emotion/styled': '^11.8.1',
      '@mui/icons-material': '^5.0.5',
      '@mui/material': '^5.8.0',
    },
    scssPre: [],
    scssPost: [],
    tsxImports: [
      `import { createTheme, ThemeProvider } from '@mui/material/styles';`,
      `import { QueryBuilderMaterial } from '@react-querybuilder/material';`,
    ],
    additionalDeclarations: [`const muiTheme = createTheme();`],
    wrapper: [
      '<ThemeProvider theme={muiTheme}><QueryBuilderMaterial>',
      '</QueryBuilderMaterial></ThemeProvider>',
    ],
    props: [],
    compileToJS: false,
    isCompatPackage: true,
    enableDnD: false,
  },
};
