import type { Column, Table } from 'drizzle-orm';
import * as drizzleOperators from 'drizzle-orm';
import type { RuleProcessor } from 'react-querybuilder';
import { defaultRuleProcessorDrizzle } from 'react-querybuilder';

// const negateIfNotOp = (op: string, sql: SQL) =>
//   op.startsWith('not') || op.startsWith('doesnot') ? not(sql) : sql;

/**
 * Given a Drizzle table config, returns a {@link react-querybuilder!index.RuleProcessor RuleProcessor}
 * for use by {@link react-querybuilder!index.formatQuery formatQuery}.
 *
 * It's probably unnecessary to call this function directly, but rather implicitly from the
 * {@link react-querybuilder!index.RuleGroupProcessor RuleGroupProcessor} generated by
 * {@link generateDrizzleRuleGroupProcessor}.
 */
export const generateDrizzleRuleProcessor =
  (table: Table | Record<string, Column>): RuleProcessor =>
  (rule, options) =>
    defaultRuleProcessorDrizzle(rule, { ...options, context: { table, drizzleOperators } });
