/**
 * Extracts fenced `ts`/`tsx` blocks from `skills/**\/*.md` into
 * `skills/__tests__/snippets/*.tsx` for typechecking (`tsc -p skills/__tests__`) and, for
 * core-only snippets, execution (`bun test ./skills`).
 *
 * Skip a block by preceding it with `<!-- snippet:skip -->`. Free variables commonly used in
 * fragments (`fields`, `query`, …) are declared in `skills/__tests__/globals.d.ts`.
 */
import { rm } from 'node:fs/promises';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');
const skillsDir = path.join(root, 'skills');
const outDir = path.join(skillsDir, '__tests__/snippets');

const fenceRegex = /(<!-- snippet:skip -->\s*\n)?^```(tsx?)\n([\s\S]*?)^```$/gm;

await rm(outDir, { recursive: true, force: true });

const written: string[] = [];
for await (const rel of new Bun.Glob('**/*.md').scan({ cwd: skillsDir })) {
  if (rel.startsWith('__')) continue;
  const src = await Bun.file(path.join(skillsDir, rel)).text();
  let i = 0;
  for (const m of src.matchAll(fenceRegex)) {
    i++;
    if (m[1]) continue;
    const line = src.slice(0, m.index).split('\n').length + (m[1] ? 1 : 0);
    const name = `${rel.replace(/\.md$/, '').replaceAll(/[/\\]/g, '__')}.${i}.tsx`;
    // `export {}` forces module scope so snippets don't collide
    const body = `// ${rel}:${line} (generated by utils/skill-snippets.ts)\n${m[3]}\nexport {};\n`;
    // oxlint-disable-next-line no-await-in-loop
    await Bun.write(path.join(outDir, name), body);
    written.push(name);
  }
}

console.log(`Extracted ${written.length} snippets to ${path.relative(root, outDir)}`);
