// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  sidebar: [
    {
      type: 'doc',
      id: 'react-querybuilder/index',
      label: 'react-querybuilder',
    },
    {
      type: 'category',
      label: 'Compatibility',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '@react-querybuilder',
        },
      ],
    },
  ],
};
