// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  sidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Index',
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules',
        },
      ],
    },
    {
      type: 'category',
      label: 'Interfaces',
      items: [
        {
          type: 'autogenerated',
          dirName: 'interfaces',
        },
      ],
    },
    {
      type: 'category',
      label: 'Namespaces',
      items: [
        {
          type: 'autogenerated',
          dirName: 'namespaces',
        },
      ],
    },
  ],
};
