name: Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - run: bun install --frozen-lockfile
      - name: Check formatting
        run: |
          bun run fmt:check || \
          (bun run fmt \
          && git --no-pager diff \
          && exit 1)
